pub mod allocator;
pub mod arpeggiator;
extern crate alloc;

pub mod benjolin;
pub mod bubble;
pub mod chorus;
pub mod convolver;
pub mod modal;
pub mod engine;
pub mod envelope;
pub mod filter;
pub mod lfo;
pub mod math;
pub mod oscillator;
pub mod params;
pub mod sample_data;
pub mod voice;
pub mod waveguide;
